
name: Update README

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  image-gen:
    name: Generate image for GitHub Stats
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        
        user: Andre601
        template: markdown
        base: activity, community, repositories, metadata
        config_timezone: Europe/Zurich
        #
        # List discussion stats
        plugin_discussions: yes
        #
        # List issue and PR stats
        plugin_followup: yes
        plugin_followup_sections: repositories, user
        #
        # Show 3D Commit calendar
        plugin_isocalendar: yes
        plugin_isocalendar_duration: half-year
        #
        # Show "Most used languages"
        plugin_languages: yes
        plugin_languages_analysis_timeout: 15
        plugin_languages_categories: markup, programming
        plugin_languages_colors: github
        plugin_languages_details: percentage
        plugin_languages_ignored: shell, hack
        plugin_languages_limit: 8
        plugin_languages_recent_categories: markup, programming
        plugin_languages_recent_days: 14
        plugin_languages_recent_load: 300
        plugin_languages_sections: most-used
        plugin_languages_threshold: 0%
        #
        # Show people following
        plugin_people: yes
        plugin_people_limit: 24
        plugin_people_size: 28
        plugin_people_types: followers
        #
        # Show recently starred
        plugin_stars: yes
        plugin_stars_limit: 5
        config_output: json

  activity:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Activity list
        uses: Readme-Workflows/recent-activity@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  placeholder_replacer:
    needs: activity
    name: Replace placeholders for README
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Pull changes for Readme-Workflows/readme-replacer
        run: git pull
      
      - name: Replace placeholders
        uses: Readme-Workflows/readme-replacer@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_FILE: './TEMPLATE.md'
          TIMEZONE: 'Europe/Zurich'
          CUSTOM_REPLACER_FILE: './.github/readme-replacer.json'
      
      - name: Push changes to TEMPLATE.md
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  stats:
    needs: placeholder_replacer
    name: Update README with latest stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull changes for probablykasper/readme-template-action
        run: git pull

      - name: Generate stats
        uses: probablykasper/readme-template-action@v1
        with:
          token: ${{ secrets.STATS_TOKEN }}

      - name: Add stats to readme
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add --all
            git commit -m "Update README with latest stats"
            git push
          fi
