
name: Update README

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  activity:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Activity list
        uses: Readme-Workflows/recent-activity@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  placeholder_replacer:
    needs: activity
    name: Replace placeholders for README
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Pull changes for Readme-Workflows/readme-replacer
        run: git pull
      
      - name: Replace placeholders
        uses: Readme-Workflows/readme-replacer@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_FILE: './TEMPLATE.md'
          TIMEZONE: 'Europe/Zurich'
      
      - name: Push changes to TEMPLATE.md
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  stats:
    needs: placeholder_replacer
    name: Update README with latest stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull changes for probablykasper/readme-template-action
        run: git pull

      - name: Generate stats
        uses: probablykasper/readme-template-action@v1
        with:
          token: ${{ secrets.STATS_TOKEN }}

      - name: Add stats to readme
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add --all
            git commit -m "Update README with latest stats"
            git push
          fi
