
name: Update README

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Update Andre601/README with new stats"
          
          URL_TEXT: "`{REPO}{ID}`"
          
          ISSUE_OPENED: "![issueOpened] {URL}"
          ISSUE_CLOSED: "![issueClosed] {URL}"
          PR_OPENED: "![PullRequestOpened] {URL}"
          PR_CLOSED: "![PullRequestClosed] {URL}"
          PR_MERGED: "![PullRequestMerged] {URL}"
          
          DISABLE_COMMENTS: true
